IcddrbProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.template import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^logout/$', auth_views.logout, name='logout_next'),
    url(r'^', include('mainApp.urls')),

]

mainApp/urls.py
from django.conf.urls import url

app_name='mainapp'
from . import views, data_views, api_views


urlpatterns = [
    url(r'^$', data_views.HomeView.as_view(), name="home"),
    url(r'^labs/$', views.LabsView.as_view(), name="labs"),
    url(r'^labs/add/$', views.LabAddView.as_view(), name="lab-add"),
    url(r'^labs/(?P<pk>[0-9]+)/$',views.LabsDetail.as_view(), name="lab-detail"),
    url(r'^labs/(?P<pk>[0-9]+)/update/$',views.LabUpdate.as_view(), name="lab-update"),

    url(r'^users/$', views.UsersView.as_view(), name="users"),
    url(r'^users/(?P<pk>[0-9]+)/$',views.UsersDetail.as_view(), name="user-detail"),
    url(r'^users/add/$',views.UserAddView.as_view(),name="user-add"),
    url(r'^users/(?P<pk>[0-9]+)/update/$',views.UserUpdateView.as_view(),name="user-update"),

    url(r'^data/add/regular/$', data_views.DataAddReView.as_view(), name="data-add-re"),
    url(r'^data/add/qc/$', data_views.QCDataAddView.as_view(), name="data-add-qc"),
    url(r'^data/qc/all/$', data_views.DataQCs.as_view(), name="data-qc"),
    url(r'^data/qc/(?P<pk>[0-9]+)/$', data_views.DataQCDetails.as_view(), name="data-qc-detail"),
    url(r'^data/qc/(?P<pk>[0-9]+)/update$', data_views.DataQCUpdate.as_view(), name="data-qc-update"),
    url(r'^data/(?P<pk>[0-9]+)/$', data_views.DataDetails.as_view(), name="data-detail"),
    url(r'^data/(?P<pk>[0-9]+)/update/$', data_views.DataUpdate.as_view(), name="data-update"),


    url(r'^qc/$', data_views.QCsView.as_view(), name="qcs"),
    url(r'^qc/add/$', data_views.QCAddView.as_view(), name="qc-add"),
    url(r'^qc/(?P<pk>[0-9]+)/$', data_views.QCDetails.as_view(), name="qc-detail"),
    url(r'^qc/(?P<pk>[0-9]+)/update/$', data_views.QCUpdateView.as_view(), name="qc-update"),


    ## ajax urls
    url(r'^get_labs_ajax/', data_views.get_labs_ajax, name="get_labs_ajax"),
    url(r'^get_users_ajax/', data_views.get_users_ajax, name="get_users_ajax"),

    ##api urls
    url(r'^api/qc/(?P<pk>[0-9]+)/$', api_views.QCRangeAPIView.as_view(), name="api-qc-range"),


]

mainApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from Districts import dist_choices
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
#Create your models here.
class Lab(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(blank=True, null=True)
    thana = models.CharField(max_length=50, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    district = models.CharField(max_length=2, choices=dist_choices)

    class Meta:
        unique_together =('name', 'thana')

    def get_absolute_url(self):
        return reverse('mainapp:lab-detail', kwargs={'pk': self.pk})

    def __str__(self):
        if self.thana:
            return self.name+':'+self.thana
        else:
            return self.name

    def get_data_points_count(self):
        ct=0
        for up in self.userprofile_set.all():
            ct+=up.user.datapoint_set.count()
        return ct

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=50)
    lab = models.ForeignKey(Lab, null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('mainapp:user-detail', kwargs={'pk': self.pk})


class DataPoint(models.Model):
    sex_choices = (
        ('M', 'MALE'),
        ('F', 'FEMALE'),
    )
    category_choices = (
        ('regular', 'REGULAR'),
        ('qc', 'QC'),
    )

    patient_id = models.CharField(max_length=50)
    patient_name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=2, choices=sex_choices, verbose_name='Sex')
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    data_category = models.CharField(max_length=10,choices=category_choices,null=True, blank=True, )
    total_cholesterol = models.IntegerField()
    high_density_lipid = models.IntegerField()
    low_density_lipid = models.IntegerField()
    tri_glycerides = models.IntegerField()
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True, blank=True)
    district = models.CharField(max_length=50,null=True, blank=True)
    note = models.TextField( null=True, blank=True)

    def get_absolute_url(self):
        return reverse('mainapp:data-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.data_category)[:2]+'_'+str(self.id)


class QC(models.Model):
    test_name = models.CharField(max_length=50)
    qc_name = models.CharField(max_length=50)
    lot = models.CharField(max_length=50)
    level_1_lower_range = models.IntegerField()
    level_2_lower_range = models.IntegerField()
    level_3_lower_range = models.IntegerField()

    level_1_upper_range = models.IntegerField()
    level_2_upper_range = models.IntegerField()
    level_3_upper_range = models.IntegerField()

    added_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True, blank=True)
    district = models.CharField(max_length=50,null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)


    def __str__(self):
        return self.test_name
    def get_absolute_url(self):
        return reverse('mainapp:qc-detail', kwargs={'pk': self.pk})

class QCData(models.Model):
    level_choices=(('1','1'),
                    ('2','2'),
                    ('3','3'))
    test_name = models.ForeignKey(QC, on_delete=models.CASCADE)
    qc_name = models.CharField(max_length=50, default='')
    level = models.CharField(max_length=10, choices=level_choices)
    value = models.IntegerField()
    remarks = models.CharField(max_length=50)
    added_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True, blank=True)
    district = models.CharField(max_length=50,null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    note = models.TextField()

    def __str__(self):
        return str(self.test_name)+str(self.id)

    def get_absolute_url(self):
        return reverse('mainapp:data-qc-detail', kwargs={'pk': self.pk})



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

mainApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

class IsAdmin(UserPassesTestMixin):
    def test_func(self):
        try:
            return 'admin' == str(self.request.user.groups.all()[0])
        except:
            return False

class LoginRequired(LoginRequiredMixin):
    login_url = '/login/'


class LabsView(IsAdmin, LoginRequired, generic.ListView):
    template_name = 'mainApp/labs.html'
    context_object_name = 'all_labs'
    search_form = SearchForm
    def get_queryset(self):
        return Lab.objects.all()

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context



class LabsDetail(IsAdmin, LoginRequired,generic.DetailView):
    model = Lab
    template_name = 'mainApp/lab_detail.html'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context

class LabAddView(IsAdmin, LoginRequired,generic.CreateView):
    model = Lab
    fields = ['name','address','thana','district']
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context



class LabUpdate(IsAdmin, LoginRequired, generic.UpdateView):
    model = Lab
    fields = ['name', 'address', 'thana', 'district']
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context


class UsersView( LoginRequired,IsAdmin, generic.ListView):
    template_name = 'mainApp/users.html'
    context_object_name = 'all_users'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context

    def get_queryset(self):
        return User.objects.all()

class UsersDetail(IsAdmin,LoginRequired,generic.DetailView):
    model = User
    template_name = 'mainApp/user_detail.html'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context


class UserAddView(IsAdmin,LoginRequired, View):

    def get(self, request):
        user_form = UserCreateForm()
        search_form = SearchForm()
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()
        return render(request, 'mainApp/user_form.html',{'form':user_form, 'search_form':search_form,'district_list':district_list,
                                                  'labs':labs,'users':users})
    def post(self, request):
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            user.userprofile.lab = user_form.cleaned_data.get('lab')
            user.userprofile.designation = user_form.cleaned_data.get('designation')
            print user_form.cleaned_data.get('role')
            if str(user_form.cleaned_data.get('role')) == 'admin':
                admin_group = Group.objects.get(name='admin')
                user.groups.add(admin_group)

            if str(user_form.cleaned_data.get('role')) == 'user':
                user_group = Group.objects.get(name='user')
                user.groups.add(user_group)
            user.save()
            return HttpResponseRedirect(reverse('mainapp:user-detail', kwargs={'pk': user.pk}))

        return render(request, 'mainApp/user_form.html', {'form': user_form})



class UserUpdateView(IsAdmin,LoginRequired,View):
    def get(self, request, pk):
        user=User.objects.get(pk=pk)
        user_form = UserUpdateForm(instance=user)
        profile_form = PofileUpdateForm(instance=user.userprofile)
        role = user.groups.all()[0]
        search_form = SearchForm()
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()
        return render(request, 'mainApp/user_form.html',{'form':user_form,'extra_form':profile_form,'role':role,'search_form':search_form,'district_list':district_list,
                                                  'labs':labs,'users':users})

    def post(self, request, pk ):
        user = User.objects.get(pk=pk)
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = PofileUpdateForm(request.POST, instance=user.userprofile)
        role = user.groups.all()[0]
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            newrole = profile_form.cleaned_data.get('role')
            oldrole = str(user.groups.all()[0])
            if newrole!=None:
                if str(newrole) != str(oldrole):
                    new_role = Group.objects.get(name=newrole)
                    user.groups.clear()
                    user.groups.add(new_role)
                    print newrole, oldrole
            profile_form.save()
            return HttpResponseRedirect(reverse('mainapp:user-detail', kwargs={'pk': user.pk}))

        return render(request, 'mainApp/user_form.html', {'form': user_form,'role':role})

mainApp/templates/mainApp/kendo_body.html
<td><a href="{% url 'mainapp:data-detail' data.id %}">{{ data }}</a></td>
<td>{{ data.patient_name }}</td>
<td>{{ data.age }}</td>
<td>{{ data.get_gender_display }}</td>
<td>{{ data.total_cholesterol }}</td>
<td>{{ data.high_density_lipid }}</td>
<td>{{ data.low_density_lipid }}</td>
<td>{{ data.tri_glycerides }}</td>
<td>{{ data.date }}</td>
<td><a href="{% url 'mainapp:user-detail' data.added_by.id %}">{{ data.added_by }}</a></td>
<td><a href="{% url 'mainapp:lab-detail' data.lab.id %}">{{ data.lab }}</a></td>

mainApp/templates/mainApp/kendo_columns.html
<th data-field="id">ID</th>
<th data-field="patient_name">Patient Name</th>
<th data-field="patient_age">Patient Age</th>
<th data-field="patient_gender">Gender</th>
<th data-field="tc">Total Cholesterol</th>
<th data-field="hdl">HDL</th>
<th data-field="ldl">LDL</th>
<th data-field="tg">TG</th>
<th data-field="date">Date</th>
<th data-field="user">Added By</th>
<th data-field="lab">Lab</th>

mainApp/templates/mainApp/kendo_columns_qc.html
<th data-field="id">ID</th>
<th data-field="date">Date</th>
<th data-field="test_name">Test Name</th>
<th data-field="level">Level</th>
<th data-field="value">Value</th>
<th data-field="remarks">Remarks</th>
<th data-field="added_by">Added By</th>
<th data-field="lab">Lab</th>

mainApp/templates/mainApp/labs.html
{% extends 'mainApp/base.html' %}
{% block body %}
    <div class="container-fluid display-screen">
        <h3><strong>All Labs</strong></h3>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Lab Name</th>
                <th>Location</th>
                <th>Number of Users</th>
                <th>Number of Datapoints</th>
                <th>Options</th>

            </tr>
            </thead>
            <tbody>
            {% for lab in all_labs %}
                <tr>
                    <td><a href="{% url 'mainapp:lab-detail' lab.id %} ">{{ lab.name }}</a></td>
                    {% if lab.thana %}
                        <td>{{ lab.thana }}, {{ lab.get_district_display }}</td>
                    {% else %}
                        <td>{{ lab.get_district_display }}</td>
                    {% endif %}
                    <td>{{ lab.userprofile_set.count }}</td>
                    <td> {{ lab.get_data_points_count }}
                        </td>
                    <td><a href="{% url 'mainapp:lab-update' lab.id %}" class="btn btn-primary">Edit</a> <a class="btn btn-danger">Delete</a></td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    <div class="display-print">
    <h3><strong>All Labs</strong></h3>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Lab Name</th>
                <th>Location</th>
                <th>Number of Users</th>
                <th>Number of Datapoints</th>


            </tr>
            </thead>
            <tbody>
            {% for lab in all_labs %}
                <tr>
                    <td>{{ lab.name }}</td>
                    {% if lab.thana %}
                        <td>{{ lab.thana }}, {{ lab.get_district_display }}</td>
                    {% else %}
                        <td>{{ lab.get_district_display }}</td>
                    {% endif %}
                    <td>{{ lab.userprofile_set.count }}</td>
                    <td> {{ lab.get_data_points_count }}
                        </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
{% endblock %}

mainApp/templates/mainApp/qc_data_detail.html
{% extends 'mainApp/base.html' %}
{% block title %}{{ qcdata }}{% endblock %}

{% block body %}
    <div class="container-fluid display-screen">
        <div class="panel panel-default">
            <div class="panel-body">
            <h3><strong>QC Data: {{ qcdata }}</strong></h3>
            	<div class="row">
                    <div class="col-sm-2">
                        <strong>Date:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.created }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Test Name:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.test_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>QC Name:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.qc_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Level:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.level }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Value:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.value }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Remarks:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.remarks }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Added By:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.added_by }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Lab:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qcdata.lab }}
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <a href="{% url 'mainapp:data-qc-update' qcdata.id %}" class="btn btn-primary">Edit</a>
                <a class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

mainApp/templates/mainApp/qc_detail.html
{% extends 'mainApp/base.html' %}
{% block title %}{{ qc }}'s Information{% endblock %}

{% block body %}
    <div class="container-fluid display-screen">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3><strong>{{ qc }}'s Information</strong></h3>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Test Name:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.test_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>QC Name:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.qc_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Lot:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.lot }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Acceptable Ranges:</strong>
                    </div>
                    <div class="col-sm-5">
                        <table class="table table-bordered table-condensed" style="width: 40%">
                            <tr>
                                <th>Level 1:</th>
                                <td>{{ qc.level_1_lower_range }} to {{ qc.level_1_upper_range }}</td>
                            </tr>
                            <tr>
                                <th>Level 2:</th>
                                <td>{{ qc.level_2_lower_range }} to {{ qc.level_2_upper_range }}</td>
                            </tr>
                            <tr>
                                <th>Level 3:</th>
                                <td>{{ qc.level_3_lower_range }} to {{ qc.level_3_upper_range }}</td>
                            </tr>

                        </table>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Created On:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.created }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Created By:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.added_by }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Last Update:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.last_updated }}
                    </div>
                </div>


                <div class="row">
                    <div class="col-sm-2">
                        <strong>Number of tests:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ qc.qcdata_set.count }}
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <a href="{% url 'mainapp:qc-update' qc.pk %}" class="btn btn-primary">Edit</a>
                <a class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
{% endblock body %}

mainApp/templates/mainApp/qcdata_form.html
{% extends 'mainApp/base.html' %}

{% block title %}
    {% if url_name == 'data-add-qc' %}
        Adding QC Data
    {% elif url_name == 'data-qc-update' %}
        Updating QC Data
    {% endif %}
{% endblock %}

{% block extra_head %}
    <style>
        .out_of_range{
            color: red;


        }

        .within_range{
            color: limegreen;


        }
    </style>
{% endblock %}

{% block body %}
    <div class="container-fluid">
    <h2>
    {% if url_name == 'data-add-qc' %}
        Adding QC Data
    {% elif url_name == 'data-qc-update' %}
        Updating QC Data: {{object}}
    {% endif %}
    </h2>
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" {% if url_name == 'data-qc-update' %} onsubmit="change_readonly()" {% endif %} action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'mainApp/form-template.html' %}
                        <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>


                    </form>

                </div>

            </div>

        </div>

    </div>
    </div>


    <script>
    function change_readonly() {
                console.log("crd called");
                $("#id_test_name").prop("disabled", false);
                $("#id_qc_name").prop("disabled", false);
                $("#id_level").prop("disabled", false);
                $("#id_remarks").prop("disabled", false);
                $("#id_note").prop("disabled", false);

                return true;
    }
    $(document).ready(function () {
        lower_range=0;
        upper_range=0;

        {% if url_name == 'data-qc-update' %}


            $("#id_test_name").prop("disabled", true);
            $("#id_qc_name").prop("disabled", true);
            $("#id_level").prop("disabled", true);
            $("#id_remarks").prop("disabled", true);
            $("#id_note").prop("disabled", true);

            var message_hide=0;
            $.get("/api/qc/"+$('#id_test_name').val()+"/?format=json", function (data, status) {
                var level = $("#id_level").val();

                if(level == 1){

                    lower_range = parseInt(data.level_1_lower_range);
                    upper_range = parseInt(data.level_1_upper_range);

                }
                else if(level == 2){

                    lower_range = parseInt(data.level_2_lower_range);
                    upper_range = parseInt(data.level_2_upper_range);

                }
                else if(level == 3){

                    lower_range = parseInt(data.level_3_lower_range);
                    upper_range = parseInt(data.level_3_upper_range);

                }

                else{
                    lower_range = 0;
                    upper_range = 0;
                    message_hide = 1;
                    $(".help-block").remove();
                }



            var message = jQuery.validator.format(`<span class="help-block">Acceptable range {0} to {1}</span>`,
                lower_range, upper_range);
            $(".help-block").remove();
            $('#id_value').parent().append(message);

            });
        {% endif %}

        {% if url_name == 'data-add-qc' %}


        $("#id_level").change(function () {
            var message_hide=0;
            $.get("/api/qc/"+$('#id_test_name').val()+"/?format=json", function (data, status) {
                var level = $("#id_level").val();

                if(level == 1){

                    lower_range = parseInt(data.level_1_lower_range);
                    upper_range = parseInt(data.level_1_upper_range);

                }
                else if(level == 2){

                    lower_range = parseInt(data.level_2_lower_range);
                    upper_range = parseInt(data.level_2_upper_range);

                }
                else if(level == 3){

                    lower_range = parseInt(data.level_3_lower_range);
                    upper_range = parseInt(data.level_3_upper_range);

                }

                else{
                    lower_range = 0;
                    upper_range = 0;
                    message_hide = 1;
                    $(".help-block").remove();
                }



            var message = jQuery.validator.format(`<span class="help-block">Acceptable range {0} to {1}</span>`,
                lower_range, upper_range);
            $(".help-block").remove();
            $('#id_value').parent().append(message);

            });
        });
        {% endif %}


        $("#id_value").keyup(function () {
            val=parseInt($(this).val());
            if((val >= lower_range) && (val <= upper_range)){
                var message = jQuery.validator.format(`<span class="help-block">Within Acceptable range {0} to {1}</span>`,
                lower_range, upper_range);
                $(".help-block").remove();
                $('#id_value').parent().append(message);

                $(".help-block").removeClass("out_of_range");
                $(".help-block").addClass("within_range");
            }
            else{

                var message = jQuery.validator.format(`<span class="help-block">Outside Acceptable range {0} to {1}</span>`,
                lower_range, upper_range);
                $(".help-block").remove();
                $('#id_value').parent().append(message);
                $(".help-block").removeClass("within_range");
                $(".help-block").addClass("out_of_range");
            }



        });

    });
    </script>
{% endblock %}